# -*- coding: utf-8 -*-
"""DziadMruz2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHz9KvZpAhIzeUfDnDSSFED-QNO5fmsH
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Tytuł aplikacji widoczny w przeglądarce
st.set_page_config(page_title="Symboliczny Dziadek Mróz", layout="centered")

# --- Główna funkcja rysująca ---
def narysuj_dziadka_mroza_symbolicznie():
    """Rysuje symboliczną reprezentację Dziadka Mroza za pomocą Matplotlib."""

    # 1. Konfiguracja płótna (rysunku)
    # Tworzymy figurę (fig) i osie (ax)
    fig, ax = plt.subplots(figsize=(6, 8))

    # Ustawienie limitów osi dla łatwiejszego pozycjonowania
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)

    # Ukrycie osi i ramek, by wyglądało jak obraz
    ax.axis('off')

    # --- Kolory ---
    KOLOR_SZATY = '#005f99'    # Ciemnoniebieski
    KOLOR_BRODY = 'white'      # Biały
    KOLOR_BERLA = '#aaaaaa'    # Srebrny/szary
    KOLOR_TWARZY = '#f0c8a8'   # Jasna cera
    KOLOR_PASA = '#d4af37'     # Złoty/żółty

    # --- Rysowanie elementów (od tła do przodu) ---

    # Ciało (prostokąt w kolorze szaty)
    cialo = patches.Rectangle((35, 20), 30, 50, color=KOLOR_SZATY, zorder=1)
    ax.add_patch(cialo)

    # Pas (cienki prostokąt)
    pas = patches.Rectangle((33, 40), 34, 5, color=KOLOR_PASA, zorder=2)
    ax.add_patch(pas)

    # Głowa (koło)
    glowa = patches.Circle((50, 75), 10, color=KOLOR_TWARZY, zorder=3)
    ax.add_patch(glowa)

    # Czapka (trójkąt i pompon)
    czapka_trojkat = patches.Polygon([[40, 75], [60, 75], [55, 95]], color=KOLOR_SZATY, zorder=4)
    ax.add_patch(czapka_trojkat)
    pompon = patches.Circle((55, 95), 3, color=KOLOR_BRODY, zorder=5)
    ax.add_patch(pompon)

    # Brody (duże białe koło/elipsa maskujące dolną część twarzy)
    broda = patches.Ellipse((50, 68), 20, 15, color=KOLOR_BRODY, zorder=4)
    ax.add_patch(broda)

    # Berło (cienka linia i gwiazda na górze)
    # Linia berła
    ax.plot([70, 70], [20, 65], color=KOLOR_BERLA, linewidth=4, solid_capstyle='round', zorder=1)
    # Górny element berła (gwiazda/kula)
    berlo_gora = patches.Circle((70, 67), 3, color='silver', zorder=2)
    ax.add_patch(berlo_gora)

    # Oczy (małe czarne kropki)
    ax.plot(45, 78, 'o', color='black', markersize=3, zorder=6)
    ax.plot(55, 78, 'o', color='black', markersize=3, zorder=6)

    # Tytuł wewnętrzny
    ax.text(50, 9, 'SYMBOLICZNY DZIADEK MRÓZ', ha='center', fontsize=12, color='darkred')

    # Ustawiamy tytuł wykresu
    ax.set_title("Rysunek geometryczny Dziadka Mroza")

    # Zwracamy obiekt figury, aby Streamlit mógł go wyświetlić
    return fig

# --- Główna sekcja Streamlit ---

st.title("🎅 Generowanie grafiki w aplikacji webowej")
st.markdown("Poniżej znajduje się symboliczny Dziadek Mróz wygenerowany na żywo za pomocą Matplotlib w Streamlit.")

# 2. Wyświetlenie obrazu za pomocą Streamlit
figura = narysuj_dziadka_mroza_symbolicznie()
st.pyplot(figura) # TUTAJ UŻYWAMY FUNKCJI STREAMLIT

st.markdown("---")
st.info("Aby uruchomić ten kod, musisz mieć zainstalowane pakiety `streamlit` i `matplotlib`.")